import { useMemo, useState } from 'react'
import { ArrowUpRight, Play, Check, ChevronLeft, ChevronRight, BookOpen, Sparkles } from 'lucide-react'
import { Board } from './Board'
import { Piece } from './Piece'
import { initialPosition, pseudoMoves, PIECE_NAMES } from '../game/engine'
import type { PieceType } from '../game/engine'
import { TUTORIAL, demoPosition, newExercise, attemptExercise } from '../game/tutorial'
const LESSONS: {type:PieceType;eyebrow:string;title:string;text:string;detail:string}[] = [
  {type:'R',eyebrow:'SIX STRAIGHT LINES',title:'The rook',text:'Slide through the edges of neighboring hexagons in any of six directions, as far as the path is clear.',detail:'Rooks cannot jump over pieces. Capture by landing on an enemy piece. Open files and the center give a rook plenty of room.'},
  {type:'B',eyebrow:'FOLLOW YOUR COLOR',title:'The bishop',text:'Travel through the corners of hexagons along six diagonals. Every landing cell stays the same color.',detail:'Each army has three bishops, one on each board color. A bishop can cross between the two hexes beside its diagonal, but cannot leap an occupied landing cell on that diagonal.'},
  {type:'N',eyebrow:'TWELVE POSSIBLE LEAPS',title:'The knight',text:'Go two cells in a rook direction, then one cell at a 60° turn to either side. All twelve destinations are shown here.',detail:'The knight jumps over everything in between. It lands on the nearest cells that are on neither a rook line nor a bishop diagonal. Knights are especially useful near the center.'},
  {type:'Q',eyebrow:'THE WHOLE GEOMETRY',title:'The queen',text:'Combine all six rook directions and all six bishop diagonals. Slide as far as the path is clear.',detail:'From the center of an empty board, a queen can reach 42 cells. Use that reach carefully: bringing the queen out too early can make it a target.'},
  {type:'K',eyebrow:'ONE STEP, TWELVE WAYS',title:'The king',text:'Move one rook step or one bishop step. That gives the king twelve possible destinations.',detail:'Your king may never enter or stay in check. It cannot move to an attacked cell, and the two kings cannot attack each other. There is no castling in Gliński’s chess.'},
  {type:'P',eyebrow:'FORWARD WITH A TWIST',title:'The pawn',text:'Advance one vacant cell straight forward. Capture one cell along either forward edge at 60° to the vertical.',detail:'A pawn on any friendly pawn starting cell may advance two clear cells. An inward capture onto another starting cell preserves this option. White heads toward the top; Black toward the bottom.'},
]
export function Learn({onTutorial,onPlay}: {onTutorial:()=>void;onPlay:()=>void}) {
  const [type,setType]=useState<PieceType>('R'),[demo,setDemo]=useState<string|null>(null),[video,setVideo]=useState(false)
  const lesson=LESSONS.find(l=>l.type===type)!,pos=useMemo(()=>demoPosition(type),[type]),from=type==='P'?'f5':'f6'
  return <div className="learn-page">
    <div className="page-heading"><div><div className="eyebrow">A NEW ANGLE ON A TIMELESS GAME</div><h1>Learn HexChess.</h1><p>Start with the basics, try each piece, then play at your own pace.</p></div><button className="button primary" onClick={onTutorial}><Sparkles size={17}/> Interactive tutorial</button></div>
    <div className="rules-intro"><div className="intro-copy"><span className="section-number">01 / THE BOARD</span><h2>Your first game, in three steps.</h2><p>HexChess follows <strong>Gliński’s hexagonal chess</strong>, created by Władysław Gliński. White moves first. Take turns moving one piece, protect your king, and checkmate your opponent.</p><ol className="quickstart"><li><strong>Select your piece.</strong> Tap or click a piece of your color.</li><li><strong>Choose its destination.</strong> Tap or click an allowed cell. In computer practice, dots show available moves.</li><li><strong>Keep your king safe.</strong> Capture enemy pieces by landing on them. Win by checkmate, not by capturing the king.</li></ol><p className="board-shades-note">The 91 hexagons use three alternating shades. Move markers sit on top of those shades; they are not the board’s colors.</p><div className="rule-stats"><div><strong>91</strong><span>cells</span></div><div><strong>18</strong><span>pieces per side</span></div><div><strong>3</strong><span>bishop colors</span></div></div></div><div className="intro-board"><Board pos={initialPosition()} compact coordinates={false}/></div></div>
    <section className="rules-section"><div className="section-heading"><div><span className="section-number">02 / THE PIECES</span><h2>How each piece moves.</h2></div><span className="muted">Choose a piece, then tap a destination dot.</span></div><div className="piece-tabs">{LESSONS.map(l=><button key={l.type} className={type===l.type?'active':''} onClick={()=>{setType(l.type);setDemo(null)}}><Piece type={l.type} color="white" size={38}/>{PIECE_NAMES[l.type]}</button>)}</div><div className="movement-layout"><div className="movement-demo"><Board pos={pos} selected={from} guided target={demo??undefined} moves={pseudoMoves(pos,from)} onCell={id=>{if(pseudoMoves(pos,from).some(m=>m.to===id))setDemo(id)}} compact/><span className="demo-caption">{demo?`${lesson.title.replace('The ','')} can reach ${demo}.`:'Dots show possible moves on this practice board.'}</span></div><div className="movement-copy"><div className="eyebrow">{lesson.eyebrow}</div><h2>{lesson.title}</h2><p className="lead">{lesson.text}</p><p>{lesson.detail}</p><div className="callout"><Sparkles size={19}/><p>These simplified boards show movement without other pieces in the way. In a game, HexChess checks blockers and your king’s safety. Move hints are available in computer practice.</p></div></div></div></section>
    <section className="rules-section beginner-winning"><span className="section-number">03 / PROTECT YOUR KING</span><h2>Understand check and checkmate.</h2><div className="ending-grid"><article><h3>Check means your king is attacked.</h3><p>Your next move must make the king safe. Move it away, capture the attacker, or block the attack when possible. You cannot ignore check.</p></article><article><h3>Checkmate wins the game.</h3><p>If the king is in check and there is no legal escape, the game ends. The attacking player wins. HexChess prevents illegal moves and tells you when the game is over.</p></article></div></section>
    <details className="rules-section rules-details"><summary><span><span className="section-number">04 / SPECIAL MOVES</span><strong>Promotion, en passant & castling</strong><small>Open when you’re ready for the finer details.</small></span><ChevronRight size={20}/></summary><div className="rule-grid">
      <article><span className="rule-icon"><Piece type="P" color="white" size={30}/></span><h3>En passant</h3><p>When an opposing pawn moves two cells and passes a cell your pawn attacks, you may capture it on that passed cell. Remove the pawn from its destination. This opportunity lasts for your very next move only.</p><p className="rule-example">Example: Black c7–c5. White b5×c6 captures the pawn on c5.</p></article>
      <article><span className="rule-icon"><Piece type="Q" color="white" size={30}/></span><h3>Promotion</h3><p>A pawn that reaches the far end of its file must become a queen, rook, bishop, or knight. Choose any of these pieces, even if your original one is still on the board. HexChess lets you choose before finishing the move.</p><p className="rule-example">The far edge has 11 promotion cells, one at the end of each file.</p></article>
      <article><span className="rule-icon"><Piece type="K" color="white" size={30}/></span><h3>No castling</h3><p>There is no castling on this board. The king moves using its normal twelve directions. Develop your pieces and use the shape of your pawn formation to keep your king safe.</p><p className="rule-example">All captures remove the enemy piece; the king is checkmated, never captured.</p></article>
    </div></details>
    <details className="rules-section rules-details"><summary><span><span className="section-number">05 / ENDINGS & CLOCKS</span><strong>Scoring, draws & time controls</strong><small>How HexChess handles the end of a game.</small></span><ChevronRight size={20}/></summary><div className="ending-grid"><article><h3>Check & checkmate</h3><p>A king is in check when an enemy piece attacks its cell. Respond by moving your king, capturing the attacker, or blocking the attack. If no legal response exists, it is checkmate and the attacker wins 1–0.</p></article><article><h3>Stalemate is a partial win</h3><p>If the player to move has no legal move and is not in check, Gliński’s rule awards <strong>¾ point to the player delivering stalemate</strong> and <strong>¼ to the stalemated player</strong>. HexChess uses this original scoring.</p></article><article><h3>Drawn positions</h3><p>HexChess automatically draws after the third occurrence of the same position with the same move rights, or 50 moves by each side without a capture or pawn move. Bare kings, and one king with a single bishop or knight against a bare king, are also drawn.</p><p>Other unusual dead positions can be drawn by agreement. Two knights can mate on a hexagonal board, so ordinary square-chess material assumptions do not apply.</p></article><article><h3>Clocks & resignation</h3><p>The active player’s clock counts down. Completing a move adds the selected increment. The clock begins after White’s opening move, and continues while the app is in the background. Running out of time loses, unless the opponent only has a bare king, when HexChess records a draw.</p><p>You can pause during computer practice. Local games keep the clock running. You can also resign or agree to a draw. Correspondence games have no clocks.</p></article></div></details>
    <section className="rules-section"><span className="section-number">06 / YOUR FIRST GAME</span><h2>A few good habits.</h2><div className="strategy-grid"><article><span>01</span><h3>Make space in the center.</h3><p>Central pieces have more directions to work with. A modest pawn advance can open a useful lane for a bishop or rook.</p></article><article><span>02</span><h3>Notice all three colors.</h3><p>Your bishops cover different territory and cannot defend one another. Coordinate them with knights, rooks, and pawns.</p></article><article><span>03</span><h3>Look twice before you move.</h3><p>Hexagonal lines can hide a distant attack. Before committing, look for checks, captures, and threats from all six sides.</p></article></div></section>
    <section className="rules-section"><span className="section-number">07 / WATCH & GO DEEPER</span><h2>A fresh way to see chess.</h2><div className="resource-layout"><div className="video-card">{video?<iframe src="https://www.youtube-nocookie.com/embed/bgR3yESAEVE" title="Chess Is Better on Hexagons" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowFullScreen/>:<button className="video-cover" onClick={()=>setVideo(true)}><div className="video-geometry">⬡</div><span className="video-play"><Play size={25} fill="currentColor"/></span><strong>Chess Is Better<br/>on Hexagons</strong><span>Watch the video that inspired HexChess</span></button>}<a className="video-fallback" href="https://youtu.be/bgR3yESAEVE" target="_blank" rel="noreferrer">Watch on YouTube <ArrowUpRight size={15}/></a></div><div className="resource-list"><a href="https://www.chessvariants.com/hexagonal.dir/hexagonal.html" target="_blank" rel="noreferrer"><BookOpen size={20}/><div><strong>The Chess Variant Pages</strong><span>Gliński’s board, piece movement, and original rules</span></div><ArrowUpRight size={17}/></a><a href="https://www.abstractgames.org/uploads/1/1/6/4/116462923/abstract_games_issue_7.pdf" target="_blank" rel="noreferrer"><BookOpen size={20}/><div><strong>Abstract Games · Issue 7</strong><span>Discussion of hexagonal chess and Gliński’s opening theory</span></div><ArrowUpRight size={17}/></a><div className="book-reference"><BookOpen size={20}/><div><strong>First Theories of Hexagonal Chess</strong><span>Władysław Gliński, 1974. A historical book on openings, strategy, and endings; often available secondhand.</span></div></div><p className="form-note">This tutorial is written for HexChess. Other sites may use different stalemate or pawn rules; this game uses the Gliński rules described above. The video requires an internet connection.</p></div></div></section>
    <div className="learn-footer"><h2>Your move.</h2><button className="button primary" onClick={onPlay}>Back to the board</button></div>
  </div>
}
export function Tutorial({onPlay,onRules}: {onPlay:()=>void;onRules:()=>void}) {
  const [exercise,setExercise]=useState(()=>newExercise(0)),[completed,setCompleted]=useState<number[]>([]),[finished,setFinished]=useState(false)
  const {step,pos,selected,done,message}=exercise,lesson=TUTORIAL[step],from=lesson.type==='P'?'f5':'f6'
  const change=(n:number)=>{setExercise(newExercise(n));setFinished(false)}
  const choose=(id:string)=>{
    const next=attemptExercise(exercise,id)
    setExercise(next)
    if(next.done&&!done)setCompleted(old=>old.includes(step)?old:[...old,step])
  }
  return <div className="tutorial-page"><div className="page-heading"><div><div className="eyebrow">LEARN BY MAKING A MOVE</div><h1>One piece at a time.</h1><p>Six short lessons. Select a piece, then choose its outlined target.</p></div><button className="button secondary" onClick={onRules}>All the rules</button></div>
    <div className="tutorial-progress" aria-label={`${completed.length} of 6 lessons practiced`}>{TUTORIAL.map((l,i)=><button key={l.type} className={`${i===step&&!finished?'current':''} ${completed.includes(i)?'complete':''}`} onClick={()=>change(i)} aria-current={i===step&&!finished?'step':undefined} aria-label={`Lesson ${i+1}: ${PIECE_NAMES[l.type]}${completed.includes(i)?', practiced':''}`}><span>{completed.includes(i)?<Check size={16}/>:i+1}</span><span>{PIECE_NAMES[l.type]}</span></button>)}</div>
    {finished?<div className="tutorial-finish"><span className="section-number">{completed.length} OF 6 LESSONS PRACTICED</span><h2>{completed.length===6?'Ready for your first game.':'Keep learning at your own pace.'}</h2><p>Try an untimed game against the beginner computer. Select your piece to see its legal moves, and take your time.</p><div className="first-game-reminders"><article><strong>White moves first.</strong><p>Players take turns making one move. Captures replace the enemy piece.</p></article><article><strong>Protect your king.</strong><p>Respond to check immediately. Checkmate wins the game.</p></article><article><strong>There is no rush.</strong><p>Keep move hints on while you learn. You can return to these lessons anytime.</p></article></div><div className="finish-actions"><button className="button primary" onClick={onPlay}>Play your first game <Play size={16}/></button>{completed.length<6&&<button className="button secondary" onClick={()=>change(TUTORIAL.findIndex((_,i)=>!completed.includes(i)))}>Practice remaining lessons</button>}<button className="text-button" onClick={onRules}>Review the full rules</button></div></div>:<div className="tutorial-layout">
      <div className="tutorial-copy"><span className="section-number">LESSON {step+1} OF 6 · {PIECE_NAMES[lesson.type].toUpperCase()}</span><h2>{lesson.title}</h2><p className="lead">{lesson.instruction}</p><ol className="lesson-steps"><li className={selected?'step-done':'step-active'}><span>{selected?<Check size={14}/>:1}</span>Select the white {PIECE_NAMES[lesson.type].toLowerCase()} on <strong>{from}</strong>.</li><li className={done?'step-done':selected?'step-active':''}><span>{done?<Check size={14}/>:2}</span>{lesson.type==='P'?'Capture on':'Move to'} the outlined target <strong>{lesson.target}</strong>.</li></ol></div>
      <div className="tutorial-tip"><div className="callout"><BookOpen size={19}/><p>{lesson.tip}</p></div></div>
      <div className="tutorial-board"><Board key={step} pos={pos} selected={selected} source={from} target={done?undefined:lesson.target} moves={selected&&!done?pseudoMoves(pos,from):[]} onCell={choose} compact coordinates={false} guided/><div className="board-legend"><span><i className="legend-target"/> Outlined target</span><span><i className="legend-move"/> Other possible moves</span></div></div>
      <div className="tutorial-controls"><div className={`lesson-feedback ${done?'success':''}`} role="status" aria-live="polite">{done&&<Check size={18}/>}<span>{message||`Start by selecting the white ${PIECE_NAMES[lesson.type].toLowerCase()}.`}</span></div><div className="lesson-actions"><button className="button primary" disabled={!done} onClick={()=>step===5?setFinished(true):change(step+1)}>{step===5?'Finish tutorial':'Next lesson'}<ChevronRight size={18}/></button>{done&&<button className="text-button" onClick={()=>change(step)}>Try again</button>}</div><div className="tutorial-navigation"><button className="text-button" disabled={step===0} onClick={()=>change(step-1)}><ChevronLeft size={16}/> Previous</button><button className="text-button" onClick={()=>step<5?change(step+1):setFinished(true)}>Skip lesson</button></div></div>
    </div>}
  </div>
}
