import { useState } from 'react'
import { ArrowUpRight, Play, Check, ChevronLeft, ChevronRight, BookOpen, Sparkles } from 'lucide-react'
import { Board } from './Board'
import { Piece } from './Piece'
import { initialPosition, pseudoMoves, PIECE_NAMES } from '../game/engine'
import type { PieceType, Position } from '../game/engine'
const LESSONS: {type:PieceType;eyebrow:string;title:string;text:string;detail:string}[] = [
  {type:'R',eyebrow:'SIX STRAIGHT LINES',title:'The rook',text:'Slide through the edges of neighboring hexagons in any of six directions, as far as the path is clear.',detail:'Rooks cannot jump over pieces. Capture by landing on an enemy piece. Open files and the center give a rook plenty of room.'},
  {type:'B',eyebrow:'FOLLOW YOUR COLOR',title:'The bishop',text:'Travel through the corners of hexagons along six diagonals. Every landing cell stays the same color.',detail:'Each army has three bishops, one on each board color. A bishop can cross between the two hexes beside its diagonal, but cannot leap an occupied landing cell on that diagonal.'},
  {type:'N',eyebrow:'TWELVE POSSIBLE LEAPS',title:'The knight',text:'Go two cells in a rook direction, then one cell at a 60° turn to either side. All twelve destinations are shown here.',detail:'The knight jumps over everything in between. It lands on the nearest cells that are on neither a rook line nor a bishop diagonal. Knights are especially useful near the center.'},
  {type:'Q',eyebrow:'THE WHOLE GEOMETRY',title:'The queen',text:'Combine all six rook directions and all six bishop diagonals. Slide as far as the path is clear.',detail:'From the center of an empty board, a queen can reach 42 cells. Use that reach carefully: bringing the queen out too early can make it a target.'},
  {type:'K',eyebrow:'ONE STEP, TWELVE WAYS',title:'The king',text:'Move one rook step or one bishop step. That gives the king twelve possible destinations.',detail:'Your king may never enter or stay in check. It cannot move to an attacked cell, and the two kings cannot attack each other. There is no castling in Gliński’s chess.'},
  {type:'P',eyebrow:'FORWARD WITH A TWIST',title:'The pawn',text:'Advance one vacant cell straight forward. Capture one cell along either forward edge at 60° to the vertical.',detail:'A pawn on any friendly pawn starting cell may advance two clear cells. An inward capture onto another starting cell preserves this option. White heads toward the top; Black toward the bottom.'},
]
export function demoPosition(type:PieceType):Position {
  const board:Position['board']={[type==='P'?'f5':'f6']:{type,color:'white'}}
  if(type==='P'){board.e5={type:'P',color:'black'};board.g5={type:'P',color:'black'}}
  return {board,turn:'white',ep:null,halfmove:0,fullmove:1}
}
export function Learn({onTutorial,onPlay}: {onTutorial:()=>void;onPlay:()=>void}) {
  const [type,setType]=useState<PieceType>('R'),[demo,setDemo]=useState<string|null>(null),[video,setVideo]=useState(false)
  const lesson=LESSONS.find(l=>l.type===type)!,pos=demoPosition(type),from=type==='P'?'f5':'f6'
  return <div className="learn-page">
    <div className="page-heading"><div><div className="eyebrow">A NEW ANGLE ON A TIMELESS GAME</div><h1>Meet your next favorite game.</h1><p>All the chess you love. A little more possibility.</p></div><button className="button primary" onClick={onTutorial}><Sparkles size={17}/> Interactive tutorial</button></div>
    <div className="rules-intro"><div className="intro-copy"><span className="section-number">01 / THE BOARD</span><h2>91 hexagons.<br/>Three colors. Endless ideas.</h2><p>HexChess follows <strong>Gliński’s hexagonal chess</strong>, created by Władysław Gliński. White moves first. Take turns moving one piece, protect your king, and checkmate your opponent.</p><div className="rule-stats"><div><strong>91</strong><span>cells</span></div><div><strong>18</strong><span>pieces per side</span></div><div><strong>3</strong><span>bishop colors</span></div></div></div><div className="intro-board"><Board pos={initialPosition()} compact coordinates={false}/></div></div>
    <section className="rules-section"><div className="section-heading"><div><span className="section-number">02 / THE PIECES</span><h2>Familiar faces. New moves.</h2></div><span className="muted">Select a piece to explore its reach.</span></div><div className="piece-tabs">{LESSONS.map(l=><button key={l.type} className={type===l.type?'active':''} onClick={()=>{setType(l.type);setDemo(null)}}><Piece type={l.type} color="white" size={38}/>{PIECE_NAMES[l.type]}</button>)}</div><div className="movement-layout"><div className="movement-demo"><Board pos={pos} selected={from} moves={pseudoMoves(pos,from)} onCell={id=>{if(pseudoMoves(pos,from).some(m=>m.to===id))setDemo(id)}} compact/><span className="demo-caption">{demo?`${lesson.title.replace('The ','')} can reach ${demo}.`:'Tap a highlighted hexagon to explore.'}</span></div><div className="movement-copy"><div className="eyebrow">{lesson.eyebrow}</div><h2>{lesson.title}</h2><p className="lead">{lesson.text}</p><p>{lesson.detail}</p><div className="callout"><Sparkles size={19}/><p>In a game, tap your piece to see only legal moves. HexChess also checks your king’s safety.</p></div></div></div></section>
    <section className="rules-section"><span className="section-number">03 / THE SPECIAL RULES</span><h2>The little details that matter.</h2><div className="rule-grid">
      <article><span className="rule-icon"><Piece type="P" color="white" size={30}/></span><h3>En passant</h3><p>When an opposing pawn moves two cells and passes a cell your pawn attacks, you may capture it on that passed cell. Remove the pawn from its destination. This opportunity lasts for your very next move only.</p><p className="rule-example">Example: Black c7–c5. White b5×c6 captures the pawn on c5.</p></article>
      <article><span className="rule-icon"><Piece type="Q" color="white" size={30}/></span><h3>Promotion</h3><p>A pawn that reaches the far end of its file must become a queen, rook, bishop, or knight. Choose any of these pieces, even if your original one is still on the board. HexChess lets you choose before finishing the move.</p><p className="rule-example">The far edge has 11 promotion cells, one at the end of each file.</p></article>
      <article><span className="rule-icon"><Piece type="K" color="white" size={30}/></span><h3>No castling</h3><p>There is no castling on this board. The king moves using its normal twelve directions. Develop your pieces and use the shape of your pawn formation to keep your king safe.</p><p className="rule-example">All captures remove the enemy piece; the king is checkmated, never captured.</p></article>
    </div></section>
    <section className="rules-section"><span className="section-number">04 / ENDING THE GAME</span><h2>Play for the king.</h2><div className="ending-grid"><article><h3>Check & checkmate</h3><p>A king is in check when an enemy piece attacks its cell. Respond by moving your king, capturing the attacker, or blocking the attack. If no legal response exists, it is checkmate and the attacker wins 1–0.</p></article><article><h3>Stalemate is a partial win</h3><p>If the player to move has no legal move and is not in check, Gliński’s rule awards <strong>¾ point to the player delivering stalemate</strong> and <strong>¼ to the stalemated player</strong>. HexChess uses this original scoring.</p></article><article><h3>Drawn positions</h3><p>HexChess automatically draws after the third occurrence of the same position with the same move rights, or 50 moves by each side without a capture or pawn move. Bare kings, and one king with a single bishop or knight against a bare king, are also drawn.</p><p>Other unusual dead positions can be drawn by agreement. Two knights can mate on a hexagonal board, so ordinary square-chess material assumptions do not apply.</p></article><article><h3>Clocks & resignation</h3><p>The active player’s clock counts down. Completing a move adds the selected increment. The clock begins after White’s opening move, and continues while the app is in the background. Running out of time loses, unless the opponent only has a bare king, when HexChess records a draw.</p><p>Pause for a break in local or computer games. You can also resign or agree to a draw. Correspondence games have no clocks.</p></article></div></section>
    <section className="rules-section"><span className="section-number">05 / YOUR FIRST GAME</span><h2>A few good habits.</h2><div className="strategy-grid"><article><span>01</span><h3>Make space in the center.</h3><p>Central pieces have more directions to work with. A modest pawn advance can open a useful lane for a bishop or rook.</p></article><article><span>02</span><h3>Notice all three colors.</h3><p>Your bishops cover different territory and cannot defend one another. Coordinate them with knights, rooks, and pawns.</p></article><article><span>03</span><h3>Look twice before you move.</h3><p>Hexagonal lines can hide a distant attack. Before committing, look for checks, captures, and threats from all six sides.</p></article></div></section>
    <section className="rules-section"><span className="section-number">06 / WATCH & GO DEEPER</span><h2>A fresh way to see chess.</h2><div className="resource-layout"><div className="video-card">{video?<iframe src="https://www.youtube-nocookie.com/embed/bgR3yESAEVE" title="Chess Is Better on Hexagons" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowFullScreen/>:<button className="video-cover" onClick={()=>setVideo(true)}><div className="video-geometry">⬡</div><span className="video-play"><Play size={25} fill="currentColor"/></span><strong>Chess Is Better<br/>on Hexagons</strong><span>Watch the video that inspired HexChess</span></button>}<a className="video-fallback" href="https://youtu.be/bgR3yESAEVE" target="_blank" rel="noreferrer">Watch on YouTube <ArrowUpRight size={15}/></a></div><div className="resource-list"><a href="https://www.chessvariants.com/hexagonal.dir/hexagonal.html" target="_blank" rel="noreferrer"><BookOpen size={20}/><div><strong>The Chess Variant Pages</strong><span>Gliński’s board, piece movement, and original rules</span></div><ArrowUpRight size={17}/></a><a href="https://www.abstractgames.org/uploads/1/1/6/4/116462923/abstract_games_issue_7.pdf" target="_blank" rel="noreferrer"><BookOpen size={20}/><div><strong>Abstract Games · Issue 7</strong><span>Discussion of hexagonal chess and Gliński’s opening theory</span></div><ArrowUpRight size={17}/></a><div className="book-reference"><BookOpen size={20}/><div><strong>First Theories of Hexagonal Chess</strong><span>Władysław Gliński, 1974. A historical book on openings, strategy, and endings; often available secondhand.</span></div></div><p className="form-note">This tutorial is written for HexChess. Other sites may use different stalemate or pawn rules; this game uses the Gliński rules described above. The video requires an internet connection.</p></div></div></section>
    <div className="learn-footer"><h2>Your move.</h2><button className="button primary" onClick={onPlay}>Back to the board</button></div>
  </div>
}
const TUTORIAL = [
  {type:'R' as PieceType,target:'f9',title:'Find the straight line.',instruction:'Move the rook from f6 to f9. A rook travels through cell edges along six straight directions.',tip:'The green dots show destinations this piece can reach.'},
  {type:'B' as PieceType,target:'d5',title:'Stay on your color.',instruction:'Move the bishop from f6 to d5. Notice how the diagonal passes through cell corners and lands on the same color.',tip:'Bishops have six diagonals. Your three bishops cover the three colors.'},
  {type:'N' as PieceType,target:'g8',title:'Take a leap.',instruction:'Jump the knight from f6 to g8: two steps straight upward, then one step at a 60° turn.',tip:'Knights can leap over other pieces. Twelve jumps are possible from the center.'},
  {type:'Q' as PieceType,target:'i3',title:'Combine the directions.',instruction:'Move the queen from f6 to i3. This is a rook line; queens can use bishop diagonals too.',tip:'A central queen can reach 42 hexagons on an empty board.'},
  {type:'K' as PieceType,target:'h5',title:'One careful step.',instruction:'Move the king from f6 to h5. This is one bishop step. Kings also move one rook step.',tip:'In a real game, a king may never move into an attack. There is no castling.'},
  {type:'P' as PieceType,target:'g5',title:'Capture at a new angle.',instruction:'Capture the black pawn on g5 with the white pawn on f5. Pawns capture along forward edges, not bishop diagonals.',tip:'Pawns advance straight ahead. On a friendly starting cell, they may advance two clear cells.'},
]
export function Tutorial({onPlay,onRules}: {onPlay:()=>void;onRules:()=>void}) {
  const [step,setStep]=useState(0),[done,setDone]=useState(false),[message,setMessage]=useState(''),[finished,setFinished]=useState(false)
  const lesson=TUTORIAL[step],from=lesson.type==='P'?'f5':'f6',start=demoPosition(lesson.type)
  const pos=done?{...start,board:{...Object.fromEntries(Object.entries(start.board).filter(([id])=>id!==from)),[lesson.target]:{type:lesson.type,color:'white' as const}}}:start
  const change=(n:number)=>{setStep(n);setDone(false);setMessage('')}
  return <div className="tutorial-page"><div className="page-heading"><div><div className="eyebrow">LEARN BY MAKING A MOVE</div><h1>A little practice. A new perspective.</h1><p>Six pieces, six short lessons. You’ve got this.</p></div><button className="button secondary" onClick={onRules}>All the rules</button></div>
    <div className="tutorial-progress" aria-label={`Lesson ${step+1} of 6`}>{TUTORIAL.map((l,i)=><button key={i} className={`${i===step?'current':''} ${i<step?'complete':''}`} onClick={()=>{change(i);setFinished(false)}} aria-label={`Lesson ${i+1}: ${PIECE_NAMES[l.type]}`}><span>{i<step?<Check size={16}/>:i+1}</span><span>{PIECE_NAMES[l.type]}</span></button>)}</div>
    <div className="tutorial-layout"><div className="tutorial-board"><Board pos={pos} selected={done?lesson.target:from} moves={done?[]:pseudoMoves(start,from)} onCell={id=>{if(done)return;if(id===lesson.target){setDone(true);setMessage('Beautiful. You found it!')}else if(id!==from)setMessage(`Try ${lesson.target}. It’s marked with a green dot.`)}} compact/></div><div className="tutorial-copy"><span className="section-number">LESSON {step+1} OF 6</span><h2>{finished?'You know the moves.':lesson.title}</h2><p className="lead">{finished?'You’re ready for your first game. Start untimed against the beginner computer, keep the move hints on, and enjoy exploring.':lesson.instruction}</p><div className="callout"><Sparkles size={20}/><p>{lesson.tip}</p></div><div className={`lesson-feedback ${done?'success':''}`} role="status">{message}</div>{finished?<button className="button primary" onClick={onPlay}>Play your first game</button>:<button className="button primary" disabled={!done} onClick={()=>{if(step===5)setFinished(true);else change(step+1)}}>{step===5?'Complete tutorial':'Next lesson'}<ChevronRight size={18}/></button>}<div className="tutorial-navigation"><button className="text-button" disabled={step===0} onClick={()=>change(step-1)}><ChevronLeft size={16}/> Previous</button><button className="text-button" onClick={()=>step<5?change(step+1):setFinished(true)}>Skip lesson</button></div></div></div>
  </div>
}
