import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { Hexagon, Grid2X2, BookOpen, GraduationCap, Settings2, ChevronRight, ChevronLeft, ChevronsLeft, ChevronsRight, Plus, RotateCcw, RefreshCw, Lightbulb, Link2, Pause, Play, Flag, Handshake, Download, Upload, Check, X, Bot, Users, Clock3, Volume2, VolumeX, Sun, Moon, WifiOff, ArrowUpRight, MonitorSmartphone, Copy, Share2, HelpCircle, Maximize2, Minimize2, Pencil, Eraser } from 'lucide-react'
import { Board } from './components/Board'
import { Piece } from './components/Piece'
import { Dialog } from './components/Dialog'
import { NewGame, MODE_LABELS } from './components/NewGame'
import { Learn, Tutorial } from './components/Learn'
import { inCheck, legalMoves, notation, opposite, outcome, PIECE_NAMES, replay } from './game/engine'
import type { Color, Move, Outcome } from './game/engine'
import { clockValues, DEFAULT_SETTINGS, exportGame, gameLink, importLink, newSession, restore, STORAGE_KEY, importGame } from './game/session'
import { canUseHints, canTakeBack, canPause, ownsTurn, playMove, offerDraw, declineDraw, zenEnabled, queuePremove, resolvePremove } from './game/controls'
import { playerColor, premoveTargets } from './game/premoves'
import type { Mode, Settings } from './game/session'
type Page = 'play' | 'learn' | 'tutorial'
type Prefs = {coordinates:boolean;hints:boolean;sound:boolean;dark:boolean;premoves:boolean;paletteVersion:number;theme:'classic'|'garden'|'stone'|'walnut'}
type InstallEvent = Event & {prompt:()=>Promise<void>;userChoice:Promise<{outcome:string}>}
const defaultPrefs:Prefs={coordinates:false,hints:true,sound:false,dark:false,premoves:true,paletteVersion:2,theme:'classic'}
function loadPrefs():Prefs {try{const saved=JSON.parse(localStorage.getItem('hexchess.preferences')||'{}');return {...defaultPrefs,...saved,theme:saved.paletteVersion===2&&['classic','garden','stone','walnut'].includes(saved.theme)?saved.theme:'classic',paletteVersion:2}}catch{return defaultPrefs}}
function timeText(ms:number) {const seconds=Math.ceil(Math.max(0,ms)/1000);return `${Math.floor(seconds/60).toString().padStart(2,'0')}:${(seconds%60).toString().padStart(2,'0')}`}
function resultText(r:Outcome) {if(r.reason==='stalemate')return `${r.winner==='white'?'White':'Black'} wins by stalemate · ¾–¼`;if(!r.winner)return `Draw · ${{'fifty-move':'50-move rule',material:'insufficient material',repetition:'threefold repetition',agreement:'by agreement',timeout:'time expired',checkmate:'checkmate',stalemate:'stalemate',resignation:'resignation'}[r.reason]}`;return `${r.winner==='white'?'White':'Black'} wins · ${r.reason}`}
function captureSound(capture:boolean) {try{const C=window.AudioContext||(window as unknown as {webkitAudioContext:typeof AudioContext}).webkitAudioContext;const a=new C(),o=a.createOscillator(),g=a.createGain();o.type='sine';o.frequency.setValueAtTime(capture?320:600,a.currentTime);o.frequency.exponentialRampToValueAtTime(capture?130:340,a.currentTime+.08);g.gain.setValueAtTime(.1,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.13);o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+.15);o.onended=()=>void a.close()}catch{/* Sound is optional. */}}
export default function App() {
  const [initial]=useState(restore),[session,setSession]=useState(initial.session),[prefs,setPrefs]=useState(loadPrefs)
  const [page,setPage]=useState<Page>('play'),[selected,setSelected]=useState<string|null>(null),[flipped,setFlipped]=useState(initial.session.settings.mode==='correspondence'?initial.session.seat==='black':initial.session.settings.side==='black'&&initial.session.settings.mode==='computer')
  const [newGame,setNewGame]=useState(false),[initialMode,setInitialMode]=useState<Mode|undefined>(),[settingsOpen,setSettingsOpen]=useState(false),[shareOpen,setShareOpen]=useState(false),[confirm,setConfirm]=useState<'resign'|'draw'|null>(null),[promotion,setPromotion]=useState<Move[]|null>(null)
  const [viewIndex,setViewIndex]=useState<number|null>(null),[hint,setHint]=useState<Move|null>(null),[hintLoading,setHintLoading]=useState(false),[thinking,setThinking]=useState(false),[now,setNow]=useState(Date.now()),[toast,setToast]=useState(initial.error|| (initial.imported?'Shared game loaded. Make your move, then send the updated link.':''))
  const [drawingMode,setDrawingMode]=useState(false),[markCount,setMarkCount]=useState(0),[clearMarks,setClearMarks]=useState(0)
  const [offlineReady,setOfflineReady]=useState(!!navigator.serviceWorker?.controller)
  const [offline,setOffline]=useState(!navigator.onLine),[installEvent,setInstallEvent]=useState<InstallEvent|null>(null),[installHelp,setInstallHelp]=useState(false),[copied,setCopied]=useState(false)
  const moveList=useRef<HTMLDivElement>(null),fileInput=useRef<HTMLInputElement>(null),shareInput=useRef<HTMLInputElement>(null),hintWorker=useRef<Worker|null>(null)
  const sessionRef=useRef(session);sessionRef.current=session
  const zen=page==='play'&&zenEnabled(session)
  const zenButton=useRef<HTMLButtonElement>(null),enterZenButton=useRef<HTMLButtonElement>(null)
  const toggleZen=()=>setSession(s=>({...s,zen:!zenEnabled(s)}))
  const {pos,positions,keys}=useMemo(()=>replay(session.moves),[session.moves])
  const notations=useMemo(()=>session.moves.map((m,i)=>notation(positions[i],m)),[session.moves,positions])
  const autoResult=useMemo(()=>outcome(pos,keys),[pos,keys]),result=session.result||autoResult
  const review=viewIndex!==null&&viewIndex<session.moves.length,shownPos=review?positions[viewIndex]:pos
  const aiTurn=session.settings.mode==='computer'&&pos.turn!==session.settings.side
  const clocks=clockValues({...session,result},pos.turn,now)
  const ownColor=playerColor(session),premoveTurn=!!ownColor&&ownColor!==pos.turn&&prefs.premoves&&!review&&!result&&!session.paused
  const checked=inCheck(pos),selectedMoves=useMemo(()=>selected?premoveTurn&&ownColor?premoveTargets(pos,selected,ownColor):legalMoves(pos,selected):[],[pos,selected,premoveTurn,ownColor])
  const captures=useMemo(()=>{
    const taken:Record<Color,typeof pos.board[string][]>={white:[],black:[]}
    session.moves.forEach((m,i)=>{const prev=positions[i],piece=prev.board[m.to]||(prev.board[m.from].type==='P'&&prev.ep?.target===m.to?prev.board[prev.ep.pawn]:undefined);if(piece)taken[opposite(piece.color)].push(piece)})
    return taken
  },[session.moves,positions])
  useEffect(()=>{try{localStorage.setItem(STORAGE_KEY,JSON.stringify(session))}catch{setToast('Storage is unavailable. Export your game to keep a copy.')}},[session])
  useEffect(()=>{document.documentElement.dataset.theme=prefs.dark?'dark':'light';document.documentElement.dataset.board=prefs.theme;try{localStorage.setItem('hexchess.preferences',JSON.stringify(prefs))}catch{/* Device preferences are optional. */}},[prefs])
  useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),200);return ()=>clearInterval(timer)},[])
  useEffect(()=>{if(session.settings.minutes>0&&session.started&&!session.paused&&!result&&clocks[pos.turn]<=0){const winner=opposite(pos.turn),hasPiece=Object.values(pos.board).some(p=>p.color===winner&&p.type!=='K');setSession(s=>({...s,clocks:clockValues(s,pos.turn),result:{reason:'timeout',winner:hasPiece?winner:null}}))}},[clocks,pos,session,result])
  useEffect(()=>{if(toast){const timer=setTimeout(()=>setToast(''),6500);return ()=>clearTimeout(timer)}},[toast])
  useEffect(()=>{moveList.current?.scrollTo({top:moveList.current.scrollHeight,behavior:'smooth'})},[session.moves.length])
  useEffect(()=>{setDrawingMode(false);setClearMarks(n=>n+1);setSelected(null)},[session.id])
  useEffect(()=>{
    if(!prefs.premoves&&session.premove){setSession(s=>({...s,premove:undefined}));return}
    const next=resolvePremove(session)
    if(next!==session){setSession(s=>s===session?next:s);setSelected(null);setNow(Date.now());setToast(next.moves.length>session.moves.length?'Premove played.':next.result?'Your game has ended.':'Premove canceled: the position changed or the move is no longer legal.')}
  },[session,prefs.premoves])
  useEffect(()=>{setSelected(null);setHint(null);setHintLoading(false);hintWorker.current?.terminate()},[pos])
  useEffect(()=>{
    if(initial.imported)history.replaceState(null,'',location.pathname+location.search)
    const onReady=()=>setOfflineReady(true)
    const onOnline=()=>setOffline(!navigator.onLine),onInstall=(e:Event)=>{e.preventDefault();setInstallEvent(e as InstallEvent)},onHash=()=>{
      if(location.hash.startsWith('#game='))try{const s=importLink(location.hash,sessionRef.current);setSession(s);setViewIndex(null);setFlipped(s.seat==='black');setPage('play');setToast('Shared game loaded. Make your move, then send the updated link.');history.replaceState(null,'',location.pathname+location.search)}catch{setToast('This game link could not be opened.')}
    }
    window.addEventListener('hexchess:offline-ready',onReady);window.addEventListener('online',onOnline);window.addEventListener('offline',onOnline);window.addEventListener('beforeinstallprompt',onInstall);window.addEventListener('hashchange',onHash)
    return ()=>{window.removeEventListener('hexchess:offline-ready',onReady);window.removeEventListener('online',onOnline);window.removeEventListener('offline',onOnline);window.removeEventListener('beforeinstallprompt',onInstall);window.removeEventListener('hashchange',onHash)}
  },[])
  const commit=useCallback((m:Move,computer=false)=>{
    const gameId=session.id
    setSession(s=>s.id===gameId?playMove(s,m,Date.now(),computer):s)
    if(prefs.sound)captureSound(!!pos.board[m.to]||(pos.board[m.from]?.type==='P'&&pos.ep?.target===m.to))
    setSelected(null);setHint(null);setPromotion(null);setNow(Date.now())
  },[prefs.sound,pos,session.id])
  useEffect(()=>{
    if(!aiTurn||result||session.paused)return
    const worker=new Worker(new URL('./game/ai.worker.ts',import.meta.url),{type:'module'})
    setThinking(true)
    let timer:ReturnType<typeof setTimeout>|undefined,cancelled=false
    const play=(move:Move|null)=>{timer=setTimeout(()=>{if(!cancelled){setThinking(false);if(move)commit(move,true)}},250)}
    worker.onmessage=e=>play(e.data.move||legalMoves(pos)[0]||null)
    worker.onerror=()=>{setToast('Computer analysis paused briefly. Continuing with a legal move.');play(legalMoves(pos)[0]||null)}
    worker.postMessage({pos,difficulty:session.settings.difficulty})
    return ()=>{cancelled=true;worker.terminate();clearTimeout(timer);setThinking(false)}
  },[aiTurn,result,session.paused,session.settings.difficulty,pos,commit])
  const onCell=(id:string)=>{
    if(drawingMode||review||result||session.paused||(!ownsTurn(session)&&!premoveTurn))return
    const targets=selectedMoves.filter(m=>m.to===id)
    if(targets.length){if(targets.some(m=>m.promotion))setPromotion(targets);else if(premoveTurn){setSession(s=>queuePremove(s,targets[0]));setSelected(null);setToast('Premove queued. It will be checked when your turn arrives.')}else commit(targets[0]);return}
    if(pos.board[id]?.color===(premoveTurn?ownColor:pos.turn))setSelected(id)
    else setSelected(null)
  }
  const startGame=(s:Settings)=>{setSession({...newSession(s),zen:true});setNewGame(false);setSelected(null);setHint(null);setViewIndex(null);setFlipped(s.mode==='computer'&&s.side==='black');setPage('play');window.scrollTo({top:0});history.replaceState(null,'',location.pathname+location.search);setToast(s.mode==='correspondence'?'Play your move, then share the updated link with your friend.':'A fresh board. Enjoy the game.')}
  const openNew=(mode?:Mode)=>{setInitialMode(mode);setNewGame(true)}
  const undo=()=>{
    if(!canTakeBack(session)||!session.moves.length)return
    const count=session.settings.mode==='computer'?(aiTurn?1:Math.min(2,session.moves.length)):1,index=session.moves.length-count
    setSession({...session,moves:session.moves.slice(0,index),clocks:session.clockHistory[index]||session.clocks,clockHistory:session.clockHistory.slice(0,index),anchor:Date.now(),started:index>0,result:null,premove:undefined})
    setViewIndex(null);setToast(count===2?'Your last turn and the computer’s response were taken back.':'Last move taken back.')
  }
  const getHint=()=>{
    if(!canUseHints(session)||result||review||aiTurn||session.paused||hintLoading)return
    setHintLoading(true);const worker=new Worker(new URL('./game/ai.worker.ts',import.meta.url),{type:'module'});hintWorker.current=worker
    worker.onmessage=e=>{setHint(e.data.move);setSelected(e.data.move?.from||null);setHintLoading(false);worker.terminate();if(e.data.move)setToast(`Try ${PIECE_NAMES[pos.board[e.data.move.from].type].toLowerCase()} ${e.data.move.from} to ${e.data.move.to}.`)}
    worker.onerror=()=>{setHintLoading(false);setToast('This hint could not be calculated. Try again.');worker.terminate()}
    worker.postMessage({pos,difficulty:'advanced',hint:true})
  }
  const pause=()=>{setSession(s=>canPause(s)?({...s,clocks:clockValues(s,pos.turn),paused:!s.paused,anchor:Date.now(),premove:undefined}):s);setNow(Date.now())}
  const exportFile=()=>{const blob=new Blob([JSON.stringify(exportGame(session),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`hexchess-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setToast('Game exported. Import it anytime to continue.')}
  const importFile=async(file:File)=>{try{if(file.size>1000000)throw new Error('This file is too large.');const imported=importGame(JSON.parse(await file.text())),s=imported.settings;setSession(imported);setViewIndex(null);setPage('play');setFlipped(s.mode==='correspondence'?imported.seat==='black':s.mode==='computer'&&s.side==='black');setToast('Game imported with fresh clocks. Computer practice can be resumed when ready.');setSettingsOpen(false)}catch(e){setToast(e instanceof Error?e.message:'Could not import that game.')}}
  const openShare=()=>{if(session.settings.mode==='correspondence'&&!session.moves.length&&!session.drawOffer){setSession(s=>({...s,seat:'black'}));setFlipped(true)};setCopied(false);setShareOpen(true)}
  const copyLink=async()=>{try{const link=gameLink(session);if(navigator.clipboard?.writeText)await navigator.clipboard.writeText(link);else{shareInput.current?.select();if(!document.execCommand('copy'))throw new Error('copy')}setCopied(true);setToast('Game link copied. Send it to your friend.')}catch{shareInput.current?.select();setToast('Select and copy the game link below.')}}
  const install=async()=>{if(installEvent){await installEvent.prompt();await installEvent.userChoice;setInstallEvent(null)}else setInstallHelp(true)}
  const changePage=(p:Page)=>{setPage(p);window.scrollTo({top:0,behavior:'smooth'})}
  const opponent:Color=session.settings.mode==='computer'?opposite(session.settings.side):session.settings.mode==='correspondence'?opposite(session.seat??'white'):flipped?'white':'black',player=opposite(opponent)
  const clockCard=(color:Color)=>{
    const computer=session.settings.mode==='computer'&&color!==session.settings.side,name=color==='white'?session.settings.whiteName:session.settings.blackName,active=pos.turn===color&&!result
    return <div className={`player-card ${active?'active':''} ${clocks[color]<30000&&session.settings.minutes?'low-time':''}`}><div className={`player-avatar ${color}`}><Piece type={computer?'N':'K'} color={color} size={34}/>{computer&&<span className="avatar-badge"><Bot size={11}/></span>}</div><div className="player-info"><strong>{name}</strong><span>{computer?`${session.settings.difficulty==='club'?'Club':session.settings.difficulty==='advanced'?'Advanced':'Beginner'} computer`:color==='white'?'White pieces':'Black pieces'}</span><div className="captured-pieces" aria-label={`${captures[color].length} captured pieces`}>{captures[color].map((p,i)=><Piece key={i} type={p.type} color={p.color} size={17}/>)}</div></div><div className="player-clock" aria-label={`${color} time ${session.settings.minutes?timeText(clocks[color]):'unlimited'}`}><span>{session.settings.minutes?timeText(clocks[color]):'∞'}</span>{active&&<small>{session.paused?'PAUSED':thinking&&computer?'THINKING':session.started?'TO MOVE':'READY'}</small>}</div></div>
  }
  const displayStatus=result?resultText(result):review?`Reviewing move ${Math.ceil((viewIndex||0)/2)}`:session.paused?'Game paused':thinking?'Computer is thinking…':session.settings.mode==='correspondence'&&!ownsTurn(session)?`Waiting for ${pos.turn==='white'?'White':'Black'}`:checked?`${pos.turn==='white'?'White':'Black'} is in check`:`${pos.turn==='white'?'White':'Black'} to move`
  const dismissNew=useCallback(()=>setNewGame(false),[]),dismissPrefs=useCallback(()=>setSettingsOpen(false),[]),dismissShare=useCallback(()=>setShareOpen(false),[]),dismissConfirm=useCallback(()=>setConfirm(null),[]),dismissInstall=useCallback(()=>setInstallHelp(false),[]),dismissPromotion=useCallback(()=>setPromotion(null),[])
  useEffect(()=>{
    if(page!=='play')return
    const onKey=(e:KeyboardEvent)=>{
      if(e.defaultPrevented||newGame||settingsOpen||shareOpen||confirm||promotion||installHelp||e.ctrlKey||e.metaKey||e.altKey)return
      if(e.target instanceof HTMLElement&&e.target.closest('input,select,textarea,[contenteditable=true]'))return
      if(e.key.toLowerCase()==='z'){e.preventDefault();setSession(s=>({...s,zen:!zenEnabled(s)}))}
      else if(e.key==='Escape'&&session.premove){e.preventDefault();setSession(s=>({...s,premove:undefined}));setSelected(null);setToast('Premove canceled.')}
      else if(e.key==='Escape'&&zen){e.preventDefault();setSession(s=>({...s,zen:false}))}
    }
    window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)
  },[page,zen,newGame,settingsOpen,shareOpen,confirm,promotion,installHelp,session.premove])
  useEffect(()=>{if(page==='play'&&!newGame)(zen?zenButton:enterZenButton).current?.focus({preventScroll:true})},[zen,page,newGame])
  return <div className={`app-shell ${zen?'is-zen':''}`}>

    <aside className="sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();changePage('play')}}><span className="brand-mark"><Hexagon size={26} strokeWidth={1.7}/><span>H</span></span><span>HexChess<span className="brand-dot">.</span></span></a><div className="sidebar-caption">A NEW ANGLE ON CHESS</div>
      <nav aria-label="Main navigation">{([{id:'play',label:'Play',icon:Grid2X2},{id:'learn',label:'Learn the rules',icon:BookOpen},{id:'tutorial',label:'Tutorial',icon:GraduationCap}] as const).map(n=><button key={n.id} aria-label={n.label} className={`nav-item ${page===n.id?'active':''}`} onClick={()=>changePage(n.id)}><n.icon size={19}/><span>{n.label}</span>{page===n.id&&<ChevronRight size={16}/>}</button>)}</nav>
      <div className="sidebar-note"><div className="mini-hexes"><Hexagon/><Hexagon/><Hexagon/></div><h3>Same pieces.<br/>More possibilities.</h3><p>Discover a familiar game from a different angle.</p><button className="text-button" onClick={()=>changePage('tutorial')}>Make your first move <ArrowUpRight size={16}/></button></div>
      <div className="sidebar-bottom"><button className="install-button" onClick={install}><MonitorSmartphone size={18}/><span>Install HexChess<small>Your board, anywhere.</small></span><Plus size={16}/></button><div className="sidebar-footer"><span><span className={`connection-dot ${offline?'offline':''}`}/>{offline?'Playing offline':import.meta.env.DEV?'Local preview':offlineReady?'Offline ready':'Preparing offline'}</span><button className="icon-button" onClick={()=>setPrefs({...prefs,dark:!prefs.dark})} aria-label={prefs.dark?'Use light theme':'Use dark theme'}>{prefs.dark?<Sun size={17}/>:<Moon size={17}/>}</button></div></div>
    </aside>
    <div className="main-area">{zen&&<header className="zen-header"><span className="brand"><Hexagon size={22}/>HexChess<span className="brand-dot">.</span></span><span className="zen-match">{MODE_LABELS[session.settings.mode]}{session.settings.mode==='correspondence'?` · You play ${session.seat}`:session.settings.minutes?` · ${session.settings.minutes} + ${session.settings.increment}`:' · Untimed'}</span><button ref={zenButton} className="zen-toggle" onClick={toggleZen} aria-label="Exit zen mode" aria-pressed={true} title="Exit zen mode (Z or Esc)"><Minimize2 size={17}/><span>Exit zen</span></button></header>}<header className="topbar"><div className="breadcrumb">{page==='play'?'The playing room':page==='learn'?'A guide to hexagonal chess':'The practice room'}<span>/</span><strong>{page==='play'?'Gliński’s chess':page==='learn'?'Rules & resources':'Your first six moves'}</strong></div><div className="topbar-actions">{page==='play'&&<button ref={enterZenButton} className="zen-toggle" onClick={toggleZen} aria-label="Enter zen mode" aria-pressed={false} title="Enter zen mode (Z)"><Maximize2 size={17}/><span>Zen mode</span></button>}<span className="variant-badge"><Hexagon size={12}/> 91 cells. One new perspective.</span><button className="icon-button" onClick={()=>setSettingsOpen(true)} aria-label="Open preferences"><Settings2 size={20}/></button></div></header>
      <main>{page==='play'?<div className="play-page"><div className="play-heading"><div><div className="eyebrow">THE CLASSIC, REIMAGINED</div><h1>Let’s play.</h1><p>Take your time. Find your angle.</p></div><button className="button secondary new-game-top" onClick={()=>openNew()}><Plus size={17}/> New game</button></div>
        <div className="game-layout"><section className="board-section" aria-label="Game board"><div className="board-topline"><span className="board-variant"><Hexagon size={15}/><strong>Gliński’s hexagonal chess</strong></span><button className="text-button" onClick={()=>changePage('learn')}><HelpCircle size={15}/> How to play</button></div>
          <div className="mobile-clocks">{clockCard(player)}{clockCard(opponent)}</div><div className="board-surface"><Board key={session.id} pos={shownPos} selected={review?null:selected} moves={prefs.hints?selectedMoves:[]} onCell={onCell} flipped={flipped} coordinates={prefs.coordinates} lastMove={session.moves[(review?viewIndex!:session.moves.length)-1]} hint={hint} interactionColor={premoveTurn?ownColor:pos.turn} premove={review?undefined:session.premove?.move} drawingMode={drawingMode} clearMarks={clearMarks} onMarksChange={setMarkCount} disabled={!!result||review||session.paused||(!ownsTurn(session)&&!premoveTurn)}/>{session.paused&&!result&&<div className="board-overlay"><span><Pause size={26}/></span><h2>A moment to pause.</h2><p>Your game will be here when you’re ready.</p><button className="button primary" onClick={pause}><Play size={16}/> Resume game</button></div>}</div>
          <div className={`board-status ${checked&&!result?'check-status':''}`} aria-live="polite"><span className={`status-mark ${result?'ended':''}`}>{thinking?<span className="thinking-dots"><i/><i/><i/></span>:result?<Check size={16}/>:checked?<Flag size={15}/>:<Hexagon size={16}/>}</span><div><strong>{displayStatus}</strong><span>{drawingMode?'Tap two hexagons to draw an arrow; tap the same one twice to circle it.':session.premove?`Premove queued: ${session.premove.move.from} → ${session.premove.move.to}${session.premove.move.promotion?' = '+session.premove.move.promotion:''}.` :premoveTurn&&selected?'Choose a possible premove destination. It will be validated after the reply.':premoveTurn?(session.settings.mode==='correspondence'?'Share your move. While waiting, select your piece to queue a premove.':'Select your piece to queue a premove while the computer thinks.'):result?'A good game is a new way to see.':review?'The live clock continues during review.':session.paused?'Clocks are stopped.':selected?`${PIECE_NAMES[pos.board[selected]?.type||'P']} on ${selected} · choose a destination`:session.settings.mode==='correspondence'?(session.drawOffer?session.drawOffer===session.seat?'Draw offered. Share the link for your friend to respond.':'Your friend offered a draw. Accept or decline below, then send the reply.':ownsTurn(session)?'Make one move, then share the updated link.':'Share this board and open your friend’s reply to continue.'):'Select a piece, then a highlighted hexagon.'}</span></div>{review?<button className="text-button" onClick={()=>setViewIndex(null)}>Return to live</button>:result?<button className="text-button" onClick={()=>openNew()}>Play again <Plus size={16}/></button>:<span className="turn-indicator"><span className={pos.turn}/>{pos.turn==='white'?'White':'Black'}</span>}</div>
          {session.premove&&<div className="premove-notice"><span>Queued for your next turn</span><button onClick={()=>{setSession(s=>({...s,premove:undefined}));setSelected(null);setToast('Premove canceled.')}}><X size={14}/> Cancel premove</button></div>}
          <div className="board-toolbar"><div>{canTakeBack(session)&&<button onClick={undo} disabled={!session.moves.length||review} title="Take back your last turn"><RotateCcw size={18}/><span>Undo</span></button>}<button onClick={()=>setFlipped(!flipped)} title="Flip the board"><RefreshCw size={18}/><span>Flip board</span></button><button aria-label="Draw arrows" aria-pressed={drawingMode} title="Right-drag to draw; right-click to circle. Shift: blue, Ctrl: red, Alt: green." onClick={()=>{setDrawingMode(!drawingMode);setSelected(null)}}><Pencil size={18}/><span>Draw</span></button>{markCount>0&&<button aria-label="Clear arrows" onClick={()=>setClearMarks(n=>n+1)}><Eraser size={18}/></button>}{canUseHints(session)&&<button onClick={getHint} disabled={!!result||aiTurn||review||session.paused||hintLoading}><Lightbulb size={18}/><span>{hintLoading?'Finding…':'Hint'}</span></button>}</div><button className="toolbar-settings" onClick={()=>setSettingsOpen(true)} aria-label="Board preferences"><Settings2 size={18}/></button></div>
          <div className="board-footnote"><span><Hexagon size={13}/> Three colors. Six directions. Your move.</span><button className="text-button" onClick={()=>changePage('tutorial')}>Try the tutorial <ChevronRight size={14}/></button></div>
        </section>
        <aside className="game-panel" aria-label="Game controls"><div className="opponent-tabs" role="group" aria-label="Choose game type">{(['computer','local','correspondence'] as Mode[]).map(mode=><button key={mode} className={session.settings.mode===mode?'active':''} onClick={()=>{if(mode!==session.settings.mode)openNew(mode)}}>{mode==='computer'?<Bot size={16}/>:mode==='local'?<Users size={16}/>:<Link2 size={16}/>}<span>{mode==='computer'?'Computer':mode==='local'?'With a friend':'By link'}</span></button>)}</div>
          {clockCard(opponent)}<div className="match-divider"><span><Clock3 size={13}/>{session.settings.minutes?`${session.settings.minutes} + ${session.settings.increment} · ${session.settings.minutes<=5?'Blitz':'Rapid'}`:'Untimed game'}</span><span>{MODE_LABELS[session.settings.mode]}</span></div>{clockCard(player)}
          <div className="moves-panel"><div className="moves-heading"><strong>Moves</strong><span>{session.moves.length?`${Math.ceil(session.moves.length/2)} ${session.moves.length<=2?'turn':'turns'}`:'A clean slate'}</span><button className="icon-button" onClick={exportFile} aria-label="Export game"><Download size={16}/></button></div><div className="move-column-labels"><span>#</span><span>White</span><span>Black</span></div><div className="move-list" ref={moveList}>{session.moves.length?Array.from({length:Math.ceil(session.moves.length/2)},(_,i)=><div className="move-row" key={i}><span>{i+1}.</span>{[i*2,i*2+1].map(index=><button key={index} disabled={!session.moves[index]} className={index===(review?viewIndex!:session.moves.length)-1?'current':''} onClick={()=>setViewIndex(index+1===session.moves.length?null:index+1)}>{session.moves[index]?notations[index]:'—'}</button>)}</div>):<div className="empty-moves"><div className="empty-hex"><Hexagon size={30}/><span>1</span></div><strong>Every game starts<br/>with a little possibility.</strong><p>Your moves will appear here.</p></div>}</div><div className="move-navigation"><button className="icon-button" disabled={!session.moves.length||(review&&viewIndex===0)} onClick={()=>setViewIndex(0)} aria-label="First position"><ChevronsLeft size={18}/></button><button className="icon-button" disabled={!session.moves.length||(review&&viewIndex===0)} onClick={()=>setViewIndex(Math.max(0,(viewIndex??session.moves.length)-1))} aria-label="Previous move"><ChevronLeft size={18}/></button><span>{review?`${viewIndex} / ${session.moves.length}`:'Current position'}</span><button className="icon-button" disabled={!review} onClick={()=>setViewIndex(viewIndex!+1===session.moves.length?null:viewIndex!+1)} aria-label="Next move"><ChevronRight size={18}/></button><button className="icon-button" disabled={!review} onClick={()=>setViewIndex(null)} aria-label="Latest position"><ChevronsRight size={18}/></button></div></div>
          <div className="game-actions">{canPause(session)&&<button onClick={pause} disabled={!!result||session.settings.mode==='correspondence'}><span>{session.paused?<Play size={17}/>:<Pause size={17}/>}</span>{session.paused?'Resume':'Pause'}</button>}<button onClick={()=>session.settings.mode==='correspondence'?setSession(offerDraw(session)):setConfirm('draw')} disabled={!!result||(session.settings.mode==='correspondence'&&(session.drawOffer===session.seat||(!session.drawOffer&&!ownsTurn(session))))}><Handshake size={18}/>{session.settings.mode==='correspondence'?session.drawOffer?session.drawOffer===session.seat?'Draw offered':'Accept draw':'Offer draw':'Draw'}</button>{session.settings.mode==='correspondence'&&session.drawOffer&&session.drawOffer!==session.seat&&!result&&<button onClick={()=>setSession(declineDraw(session))}>Decline draw</button>}<button onClick={()=>setConfirm('resign')} disabled={!!result}><Flag size={17}/>Resign</button></div>
          <button className="button share-button" onClick={openShare}><Link2 size={17}/>{session.settings.mode==='correspondence'?'Share game link':'Share a game'}<ArrowUpRight size={16}/></button><div className="panel-tip"><span>GOOD TO KNOW</span><p>{session.settings.mode==='correspondence'?'The whole game travels in the link. Send it back and forth to take turns.':'With three bishops, every color has its own quiet power.'}</p><button className="text-button" onClick={()=>changePage('learn')}>Explore the rules <ChevronRight size={13}/></button></div>
        </aside></div>
      </div>:page==='learn'?<Learn onTutorial={()=>changePage('tutorial')} onPlay={()=>changePage('play')}/>:<Tutorial onRules={()=>changePage('learn')} onPlay={()=>startGame({...DEFAULT_SETTINGS,minutes:0,increment:0,difficulty:'beginner'})}/>}
      </main><footer className="main-footer"><span>HexChess <span>·</span> A different kind of classic.</span><span>Made for the love of the game <Hexagon size={12}/></span></footer>
    </div>
    {newGame&&<NewGame current={session.settings} initialMode={initialMode} onStart={startGame} onClose={dismissNew}/>}
    {settingsOpen&&<Dialog title="Your board. Your way." subtitle="A few little things to make it feel like home." onClose={dismissPrefs}>
      <div className="field-label">BOARD PALETTE</div><div className="palette-picker">{(['classic','garden','stone','walnut'] as const).map(t=><button className={prefs.theme===t?'active':''} key={t} onClick={()=>setPrefs({...prefs,theme:t})}><span className={`palette-swatch ${t}`}><i/><i/><i/></span><span>{t==='classic'?'Classic':t==='garden'?'Garden':t==='stone'?'Slate':'Walnut'}</span>{prefs.theme===t&&<Check size={15}/>}</button>)}</div>
      {[{key:'coordinates',title:'Cell coordinates',text:'Show the name of every hexagon.'},{key:'hints',title:'Legal move highlights',text:'See where your selected piece can move.'},{key:'premoves',title:'Premoves',text:'Queue one move while the computer or your link-game friend plays.'},{key:'sound',title:'Move sounds',text:'A gentle note with every move.'},{key:'dark',title:'Dark appearance',text:'A quieter board for late-night games.'}].map(item=><label className="preference-row" key={item.key}><span><strong>{item.title}</strong><small>{item.text}</small></span><input type="checkbox" checked={prefs[item.key as keyof Pick<Prefs,'coordinates'|'hints'|'premoves'|'sound'|'dark'>]} onChange={e=>setPrefs({...prefs,[item.key]:e.target.checked})}/><span className="switch"/></label>)}
      <div className="dialog-divider"/><div className="field-label">KEEP YOUR GAME</div><div className="two-buttons"><button className="button secondary" onClick={exportFile}><Download size={16}/> Export game</button><button className="button secondary" onClick={()=>fileInput.current?.click()}><Upload size={16}/> Import game</button></div><button className="button secondary full-width install-in-prefs" onClick={()=>{setSettingsOpen(false);void install()}}><MonitorSmartphone size={17}/> Install HexChess</button><p className="form-note small">Right-drag to draw arrows; right-click a cell to circle it. Repeat a drawing to remove it. Outside Draw mode, left-click or a move clears drawings. Premoves are speculative and execute only if legal when your turn arrives.</p><p className="form-note small">Your current game is saved on this device. Exports keep the move history and settings. Importing a timed game gives both players fresh clocks.</p>
    </Dialog>}
    {shareOpen&&<Dialog title="Good games are worth sharing." subtitle="Play together, one link at a time." onClose={dismissShare}><div className="share-illustration"><Hexagon size={66} strokeWidth={1.2}/><Link2 size={26}/></div><div className="share-steps"><p><span>1</span>Send this link to your friend.</p><p><span>2</span>They open the board and play their assigned color.</p><p><span>3</span>They share the updated link back to you.</p></div><div className="share-notice">{session.moves.length?`This link includes all ${session.moves.length} moves. `:'This link opens a fresh board. '}It creates an untimed correspondence game. You each play one color. Links are snapshots; always use the newest reply. Saved history rejects conflicting moves on this device.</div><label className="field-label" htmlFor="share-link">YOUR GAME LINK</label><div className="share-link-field"><input ref={shareInput} id="share-link" readOnly value={gameLink(session)} onFocus={e=>e.target.select()}/><button className="icon-button" onClick={copyLink} aria-label="Copy game link">{copied?<Check size={18}/>:<Copy size={18}/>}</button></div><button className="button primary full-width" onClick={copyLink}>{copied?<Check size={18}/>:<Link2 size={18}/>} {copied?'Link copied':'Copy game link'}</button>{!!navigator.share&&<button className="button secondary full-width native-share" onClick={async()=>{try{await navigator.share({title:'Your move on HexChess',text:'Let’s play hexagonal chess. Open the board, make your move, and share the updated link back.',url:gameLink(session)})}catch{/* Dismissal does not change the game. */}}}><Share2 size={16}/> Share with…</button>}<p className="form-note small center">Friendly offline play. Links cannot verify identity or prevent outside engine assistance.</p></Dialog>}
    {confirm&&<Dialog title={confirm==='resign'?'Call it a good game?':'Meet in the middle?'} subtitle={confirm==='resign'?'Resigning ends this game.':'End the game as a draw by agreement.'} onClose={dismissConfirm}><p className="confirm-copy">{confirm==='resign'?`${(session.settings.mode==='computer'?session.settings.side:session.settings.mode==='correspondence'?session.seat:pos.turn)==='white'?'White':'Black'} will resign. You can review the moves afterward or start a fresh game.`:session.settings.mode==='computer'?'You can end this practice game as a draw. Your move history stays available to review.':'Both players should agree before ending the game as a draw. For link games, check with your friend before sharing the finished board.'}</p><div className="two-buttons"><button className="button secondary" onClick={dismissConfirm}>Keep playing</button><button className="button primary" onClick={()=>{const resigning=session.settings.mode==='computer'?session.settings.side:session.settings.mode==='correspondence'?session.seat??pos.turn:pos.turn;setSession({...session,clocks:clockValues(session,pos.turn),result:{reason:confirm==='resign'?'resignation':'agreement',winner:confirm==='resign'?opposite(resigning):null}});setConfirm(null)}}>{confirm==='resign'?'Resign game':'Agree to draw'}</button></div></Dialog>}
    {promotion&&<Dialog title="A new possibility." subtitle="Choose the piece your pawn becomes." onClose={dismissPromotion}><div className="promotion-choices">{promotion.map(m=><button key={m.promotion} onClick={()=>{if(premoveTurn){setSession(s=>queuePremove(s,m));setSelected(null);setPromotion(null);setToast('Promotion premove queued.')}else commit(m)}}><Piece type={m.promotion!} color={pos.board[m.from]?.color??pos.turn} size={64}/><span>{PIECE_NAMES[m.promotion!]}</span></button>)}</div></Dialog>}
    {installHelp&&<Dialog title="Take your board with you." subtitle="Install HexChess for a little more focus." onClose={dismissInstall}><div className="install-instructions"><p><strong>iPhone & iPad</strong><br/>Open HexChess in Safari, tap the Share button, then “Add to Home Screen”.</p><p><strong>Android</strong><br/>Open HexChess in Chrome, use the browser menu, then “Install app” or “Add to Home screen”.</p><p><strong>Desktop</strong><br/>Use the install icon in your browser’s address bar, or find “Install HexChess” in the browser menu.</p><div className="callout"><WifiOff size={20}/><p>After the first visit, your board, computer opponent, rules, and tutorial work offline. Installation requires localhost or a secure HTTPS address.</p></div></div></Dialog>}
    <input type="file" accept="application/json,.json" hidden ref={fileInput} onChange={e=>{const file=e.target.files?.[0];if(file)void importFile(file);e.target.value=''}}/>
    {toast&&<div className="toast" role="status"><Hexagon size={18}/><span>{toast}</span><button onClick={()=>setToast('')} aria-label="Dismiss notification"><X size={16}/></button></div>}
    <button className="sound-floating" onClick={()=>setPrefs({...prefs,sound:!prefs.sound})} aria-label={prefs.sound?'Mute move sounds':'Enable move sounds'} title={prefs.sound?'Mute sounds':'Enable sounds'}>{prefs.sound?<Volume2 size={16}/>:<VolumeX size={16}/>}</button>
  </div>
}
